### ISSUE TITLE
구글로그인을 시도하면 Crash 됩니다.

### ISSUE THREAD

**Issue by Bluesky817** [coolishbee/universal-sdk-unity#12]
## What did you do?

> Please describe what you did before you encounter the issue.

## What did you expect?

> Please describe what you did expect to happen.

## What happened actually?

구글로그인을 시도하면 Crash 됩니다.

## Your environment?

Universal SDK  0.1.5
Unity 2021.3.11f
Android 10

## Screenshots or Log

2022-11-25 11:31:52.451 24034 24034 Error AndroidRuntime FATAL EXCEPTION: main
2022-11-25 11:31:52.451 24034 24034 Error AndroidRuntime Process: com.YST.Nuwemaru, PID: 24034
2022-11-25 11:31:52.451 24034 24034 Error AndroidRuntime java.lang.NoClassDefFoundError: Failed resolution of: Lio/github/jameschun7/LoginType;
2022-11-25 11:31:52.451 24034 24034 Error AndroidRuntime 	at com.universal.sdk.unitywrapper.activity.UniversalSdkWrapperActivity.getLoginIntent(UniversalSdkWrapperActivity.kt:72)
2022-11-25 11:31:52.451 24034 24034 Error AndroidRuntime 	at com.universal.sdk.unitywrapper.activity.UniversalSdkWrapperActivity.startPubSdkLoginActivity(UniversalSdkWrapperActivity.kt:107)
2022-11-25 11:31:52.451 24034 24034 Error AndroidRuntime 	at com.universal.sdk.unitywrapper.activity.UniversalSdkWrapperActivity.onCreate(UniversalSdkWrapperActivity.kt:37)
2022-11-25 11:31:52.451 24034 24034 Error AndroidRuntime 	at android.app.Activity.performCreate(Activity.java:7963)
2022-11-25 11:31:52.451 24034 24034 Error AndroidRuntime 	at android.app.Activity.performCreate(Activity.java:7952)
2022-11-25 11:31:52.451 24034 24034 Error AndroidRuntime 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
2022-11-25 11:31:52.451 24034 24034 Error AndroidRuntime 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3629)
2022-11-25 11:31:52.451 24034 24034 Error AndroidRuntime 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3806)
2022-11-25 11:31:52.451 24034 24034 Error AndroidRuntime 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
2022-11-25 11:31:52.451 24034 24034 Error AndroidRuntime 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
2022-11-25 11:31:52.451 24034 24034 Error AndroidRuntime 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
2022-11-25 11:31:52.451 24034 24034 Error AndroidRuntime 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2267)
2022-11-25 11:31:52.451 24034 24034 Error AndroidRuntime 	at android.os.Handler.dispatchMessage(Handler.java:107)
2022-11-25 11:31:52.451 24034 24034 Error AndroidRuntime 	at android.os.Looper.loop(Looper.java:237)
2022-11-25 11:31:52.451 24034 24034 Error AndroidRuntime 	at android.app.ActivityThread.main(ActivityThread.java:8167)
2022-11-25 11:31:52.451 24034 24034 Error AndroidRuntime 	at java.lang.reflect.Method.invoke(Native Method)
2022-11-25 11:31:52.451 24034 24034 Error AndroidRuntime 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
2022-11-25 11:31:52.451 24034 24034 Error AndroidRuntime 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
2022-11-25 11:31:52.451 24034 24034 Error AndroidRuntime Caused by: java.lang.ClassNotFoundException: io.github.jameschun7.LoginType
2022-11-25 11:31:52.451 24034 24034 Error AndroidRuntime 	... 18 more

**Comment by coolishbee** [comment]
안녕하세요
혹시 Plugin 폴더 path 위치가 맞게 설정됐는지 [가이드 문서](https://github.com/coolishbee/universal-sdk-unity/blob/main/docs/ko/README.md)나 [데모 프로젝트](https://github.com/coolishbee/universal-sdk-unity-demo)를 보시고 한번 확인해보시겠어요?

**Comment by Bluesky817** [comment]
-----Original Message-----

**Comment by Bluesky817** [comment]
안녕하세요. 

답변 고맙습니다.

파일 하나가 옮겨지지 않아서 나타난 문제였네요.

빌드는 성공했는데 로그인 과정에서 에러가 발생했습니다.


"Login Failed.(12500)"

12500 에러인데 이건 뭘까요?

**Comment by Bluesky817** [comment]
> 안녕하세요 혹시 Plugin 폴더 path 위치가 맞게 설정됐는지 [가이드 문서](https://github.com/coolishbee/universal-sdk-unity/blob/main/docs/ko/README.md)나 [데모 프로젝트](https://github.com/coolishbee/universal-sdk-unity-demo)를 보시고 한번 확인해보시겠어요?

**Comment by coolishbee** [comment]
12500 : 
* Firebase 콘솔 > 프로젝트 설정 > 일반 > 지원 이메일 설정 해주시면 됩니다.

![firebase-setting](https://user-images.githubusercontent.com/20632507/204142450-017ad14c-9fd5-476e-853c-fdc1403a03c3.png)

10 : 
* Firebase 프로젝트에 등록된 앱 인증서 SHA  빌드된 apk 인증서와 일치해야 함
* [구글 콘솔API](https://console.cloud.google.com/apis/credentials) 에 WebClient ID 확인

> 참고 : https://stackoverflow.com/questions/47632035/google-sign-in-error-12500
